apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zammad-pg
  namespace: zammad
spec:
  instances: 2
  storage:
    size: 3Gi
  bootstrap:
    initdb:
      database: zammad_production
      owner: zammad
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: zammad-pg-backup
