apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zammad-pg-backup-s3-creds
  namespace: zammad
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zammad-aws-secretsmanager
    kind: SecretStore
  target:
    name: zammad-pg-backup-s3-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: zammad-pg-backup-s3-creds
